package org.srtingres.helper.model

val originTest =
    """
<string name="all_alert_content_back">Information won’t be kept if you return to the last step.</string>
    <string name="all_alert_content_not_get_code">If you\'re having trouble receiving the code. Please try again later or contact us.</string>
    <string name="all_alert_content_update_notice">A newer version of the app is available.</string>
    <string name="all_alert_content_went_wrong">The process will be ended. Please try again later.</string>
    <string name="all_alert_message_retry_later">Something went wrong, please try again.</string>
    <string name="all_alert_title_announcement">Announcement</string>
    <string name="all_alert_title_back">Data Unsaved</string>
    <string name="all_alert_title_error">Error</string>
    <string name="all_alert_title_not_get_code">Didn\'t Get OTP Code?</string>
    <string name="all_alert_title_oops">Oops!</string>
    <string name="all_alert_title_update_notice">Update Notice</string>
    <string name="all_alert_title_went_wrong">Something Went Wrong</string>
    <string name="all_base_contact_us">Contact Us</string>
    <string name="all_button_apply">Apply</string>
    <string name="all_button_call">Call</string>
    <string name="all_button_cancel">Cancel</string>
    <string name="all_button_close">Close</string>
    <string name="all_button_confirm">Confirm</string>
    <string name="all_button_create">Create</string>
    <string name="all_button_done">Done</string>
    <string name="all_button_got_it">Got It</string>
    <string name="all_button_help">Help</string>
    <string name="all_button_leave">Leave</string>
    <string name="all_button_login">Log In</string>
    <string name="all_button_next">Next</string>
    <string name="all_button_ok">OK</string>
    <string name="all_button_please_retry">Please Retry</string>
    <string name="all_button_please_retry_error_code">Please Retry(%s)</string>
    <string name="all_button_remove">Remove</string>
    <string name="all_button_reset">Reset</string>
    <string name="all_button_reset_password">Reset Password</string>
    <string name="all_button_save">Save</string>
    <string name="all_button_send_invitation">Send Invitation</string>
    <string name="all_button_share">Share</string>
    <string name="all_button_stay">Stay</string>
    <string name="all_button_try_again">Try Again</string>
    <string name="all_button_update">Update</string>
    <string name="all_button_verify">Verify</string>
    <string name="all_button_yes">Yes</string>
    <string name="all_button_later">Later</string>

    <string name="all_cashier">Cashier</string>
    <string name="all_error_msg_decrypt_failed">Task completed, please check the result later.</string>
    <string name="all_error_msg_please_follow_the_rule">Please follow the rule.</string>
    <string name="all_error_msg_unknown_host">Cannot access server, please try again later.</string>
    <string name="all_label_Invite">Invite</string>
    <string name="all_label_deactivate">Deactivate</string>
    <string name="all_label_dob">Date of Birth (DD-MM-YYYY)</string>
    <string name="all_label_no_data_found">No Data Found</string>
    <string name="all_label_to">To</string>
    <string name="all_label_pin_code">PIN</string>
    <string name="all_place_holder_date">DD-MM-YYYY</string>
    <string name="base_alert_unlink_content">Unlink “%s” from this branch. You can re-link anytime.</string>
    <string name="base_alert_unlink_title">Confirm to Unlink?</string>
    <string name="base_contact_bottom_sheet_button_call">Call </string>
    <string name="base_contact_bottom_sheet_content">For applying a CUBC merchant account or recover username, please contact us. We are pleased to assist you 24/7.</string>
    <string name="base_contact_bottom_sheet_title">Need Help?</string>
    <string name="base_input_error_nickname_empty">Nickname cannot be empty.</string>
    <string name="base_input_error_id_number_empty">NID Number cannot be empty.</string>
    <string name="base_input_error_passport_number_empty">Passport Number cannot be empty.</string>
    <string name="base_label_nickname">Nickname</string>
    <string name="base_language_item_cn">简体中文</string>
    <string name="base_language_item_en">English</string>
    <string name="base_language_item_kh">ខ្មែរ</string>
    <string name="base_language_item_tw">繁體中文</string>
    <string name="base_login_alert_incorrect_input_msg">Incorrect username or password. Please check your details and try again.</string>
    <string name="base_login_alert_login_failed_title">Login Failed</string>
    <string name="base_login_button_forgot">Forgot?</string>
    <string name="base_login_label_password">Password</string>
    <string name="base_login_label_user_name">Username</string>
    <string name="base_offline_dialog_content">Please check your connection and reload.</string>
    <string name="base_offline_dialog_title">You\'re Offline</string>
    <string name="base_otp_caption_title">Enter OTP Ｗe Sent to</string>
    <string name="base_otp_alert_message_back_to_last_step">Information will not be retained once you back to the last step.</string>
    <string name="base_otp_alert_title_back_to_last_step">Back to last step?</string>
    <string name="base_otp_title">Enter OTP on</string>
    <string name="base_otp_resend">Resend</string>
    <string name="base_otp_resend_count_down">Resend %s</string>
    <string name="base_otp_resend_limit_reached">Resend Limit Reached</string>
    <string name="base_otp_resend_toast_success">New OTP sent</string>
    <string name="base_otp_send_otp">Send OTP</string>
    <string name="base_permission_button_not_allow">Don\'t Allow</string>
    <string name="base_permission_camera_alert_content">Please go to \"Device Settings\" and enable your camera access.</string>
    <string name="base_permission_camera_alert_title">Camera Access Required</string>
    <string name="base_permission_gallery_alert_content">Please go to \"Device Settings\" to enable access.</string>
    <string name="base_permission_gallery_alert_title">Gallery Access Required</string>
    <string name="base_permission_location_alert_content">Please go to \"Device Setting\" and enable your location access.</string>
    <string name="base_permission_location_alert_title">Location Access Required</string>
    <string name="base_permission_notification_alert_content">Please go to \"Device Settings\" to enable notifications.</string>
    <string name="base_permission_notification_alert_title">Notification Access Required</string>
    <string name="base_permission_notification_content">Enable notification to get all transaction and promotion messages.</string>
    <string name="base_permission_notification_title">Don\'t Miss Out!</string>
    <string name="base_permission_storage_alert_content">Please go to \"Device Settings\" and enable your storage access.</string>
    <string name="base_permission_storage_alert_title">Storage Access Required</string>
    <string name="base_pop_up_will_timeout_msg">In %s seconds inactive mode will start. Tap continue if you want to keep using.</string>
    <string name="base_pop_up_will_timeout_title">Session Timeout</string>
    <string name="base_register_idNumber">IdNumber</string>
    <string name="base_register_mobile">Mobile Number</string>
    <string name="base_select_language_en">English</string>
    <string name="base_select_language_kh">ភាសាខ្មែរ</string>
    <string name="base_select_language_title">Select Language</string>
    <string name="base_terms_uncheck_alert_content">Please agree to CUBC T&amp;C Policy to continue.</string>
    <string name="base_terms_uncheck_alert_title">Terms Agreed</string>
    <string name="base_register_error_msg_invalid_dob">Please enter a valid date of birth.</string>
    <string name="base_register_error_msg_invalid_nid">Your NID Number is invalid.</string>
    <string name="base_terms_alert_message_disagree">If you do not agree the terms and conditions, the setting process would be terminated.</string>
    <string name="base_terms_alert_title_disagree">Terms and Privacy Policy</string>
    <string name="base_terms_title">I agree <![CDATA[<font color=#00994E><b>Terms &amp; Privacy Policy.</b></font>]]></string>
    <string name="base_upgrade_version_dialog_message">A new app version is ready. Please update to continue. This will only take a few minutes.</string>
    <string name="base_upgrade_version_dialog_title">Time to Update</string>
    <string name="business_management_add_new_cashiers">New Cashier</string>
    <string name="business_management_alert_deactivate_msg">All info related to \"%s\" will be permanently deleted and cannot be undone.</string>
    <string name="business_management_alert_deactivate_title">Confirm to Deactivate</string>
    <string name="business_management_alert_name_taken_msg">Please use a new name.</string>
    <string name="business_management_alert_name_taken_title">Name Taken</string>
    <string name="business_management_alert_phone_taken_msg">Please use a new phone number.</string>
    <string name="business_management_alert_phone_taken_title">Phone Number Taken</string>
    <string name="business_management_alert_reset_limit_msg">Too many password reset attempts. Please try again tomorrow.</string>
    <string name="business_management_alert_reset_limit_title">Reset Limit Reached</string>
    <string name="business_management_alert_reset_password_msg">A temporary password will be sent to \"%s\" to reset password.</string>
    <string name="business_management_alert_reset_password_title">Reset Password Request</string>
    <string name="business_management_bottom_sheet_branch_info">Branch Info</string>
    <string name="business_management_bottom_sheet_notify_title">Stay Updated!</string>
    <string name="business_management_bottom_sheet_title">Link Branches</string>
    <string name="business_management_branch_info">Info</string>
    <string name="business_management_business_deactivated_description">%s is deactivated.</string>
    <string name="business_management_caption_title_confirmation">Confirmation</string>
    <string name="business_management_caption_title_detail">Cashier Management</string>
    <string name="business_management_caption_title_enter_cashier">Enter Cashier Info</string>
    <string name="business_management_caption_title_pin">Enter PIN</string>
    <string name="business_management_cashier_state_active">Active</string>
    <string name="business_management_cashier_state_deactivated">Deactivated</string>
    <string name="business_management_cashier_state_locked">Locked</string>
    <string name="business_management_cashier_state_pending">Pending</string>
    <string name="business_management_cashier_state_resetting">Resetting</string>
    <string name="business_management_cashier_state_restricted">Restricted</string>
    <string name="business_management_cashier_unlinked_toast_content">Cashier Unlinked</string>
    <string name="business_management_cashiers_layer_header">Linked Cashiers</string>
    <string name="business_management_deactivated_branch_notice">Branch is deactivated.\nContact us for details.</string>
    <string name="business_management_deactivated_branches_notice">All branches deactivated.\nContact us for details.</string>
    <string name="business_management_empty_branch_notice_layer_content">Set up branches to unlock smarter business management!</string>
    <string name="business_management_empty_branch_notice_layer_cta">No Branch Yet</string>
    <string name="business_management_former_cashiers_layer_content">Former Cashiers</string>
    <string name="business_management_label_to">To:</string>
    <string name="business_management_link_cashier_cta">Link</string>
    <string name="business_management_link_existing_title">Link Existing Cashiers</string>
    <string name="business_management_notification">Notification</string>
    <string name="business_management_notification_branch_content">Ｍanage notifications for each branch individually.</string>
    <string name="business_management_result_label_view_details">View details</string>
    <string name="business_management_result_link_cashiers_message">Link %1s Cashiers</string>
    <string name="business_management_result_link_single_cashiers_message">Link %1s Cashier</string>
    <string name="business_management_result_link_success_message">All Cashiers are successfully linked.</string>
    <string name="business_management_result_share_link_message">Share link to invite the new cashier.</string>
    <string name="business_management_result_single_link_success_message">Cashier is successfully linked.</string>
    <string name="business_management_title_device_information">Device Information</string>
    <string name="business_management_toast_cashier_deactivate_error">Cashier deactivate error,please retry</string>
    <string name="business_management_toast_cashier_deactivated">Cashier deactivated</string>
    <string name="business_management_toast_reset_link_error">Reset link error, please retry</string>
    <string name="business_management_toast_reset_link_sent">Reset link sent</string>
    <string name="temp_business_management_no_linked_cashier">No Linked Cashier</string>
    <string name="home_alert_api_error_refresh_msg">Click try again to refresh.</string>
    <string name="home_alert_no_branch_msg">Please contact us to create one.</string>
    <string name="home_alert_no_branch_title">No Branch Found</string>
    <string name="home_go_select_business_title">Grow Your Business!</string>
    <string name="home_khqr_button_title_show_qr">Show QR</string>
    <string name="home_membership_code">Membership Code</string>
    <string name="home_select_branch_title">Select Branch</string>
    <string name="home_toast_currency_changed">Currency Changed</string>
    <string name="home_toast_membership_code_applied">Membership Code Applied</string>
    <string name="home_toast_membership_code_removed">Membership Code Removed</string>
    <string name="home_toast_pleas_select_a_branch">Please Select A Branch</string>
    <string name="login_binding_bottom_sheet_btn_start">Start</string>
    <string name="login_binding_bottom_sheet_content">For your security,  complete device binding to continue using CUBC Merchant.</string>
    <string name="login_binding_bottom_sheet_title">Get Ready!</string>
    <string name="login_home_already_applied_offline">Already Applied Offline?</string>
    <string name="login_home_btn_register">Register</string>
    <string name="login_not_me_bottom_sheet_new_user">New User</string>
    <string name="login_not_me_bottom_sheet_other_users">Other Users</string>
    <string name="login_pin_hi">Hi,</string>
    <string name="login_pin_not_you"><u>Not you?</u></string>
    <string name="login_title_cubc" translatable="false">CUBC</string>
    <string name="login_title_merchant" translatable="false">Merchant</string>
    <string name="login_title_welcome_to" translatable="false">Welcome to</string>
    <string name="qrcode_bank_hotline">Bank Hotline : %s</string>
    <string name="qrcode_error_msg_exceed_amount">Amount exceeds the 12-character limit. Please reduce to continue.</string>
    <string name="qrcode_error_msg_min_amount">The amount must be greater than 100 Cambodian riel to proceed.</string>
    <string name="qrcode_error_title_exceed_amount">Amount Limit Exceeded</string>
    <string name="qrcode_error_title_min_amount">Minimum Amount Required</string>
    <string name="qrcode_expired_alert_msg">"Please generate a new code to continue."</string>
    <string name="qrcode_expired_alert_title">QR Code Expired.</string>
    <string name="qrcode_toast_khqr_save_success">KHQR Save</string>
    <string name="qrcode_toast_khqr_share_success">KHQR Shared</string>
    <string name="register_cashier_info_alert_activate_fail_title">Activation Failed</string>
    <string name="register_cashier_info_alert_incorrect_phone_msg">Incorrect phone number. Please check and try again.</string>
    <string name="register_cashier_info_caption_subtitle">Join as a cashier via your phone within 72 hours.</string>
    <string name="register_cashier_info_label_by">by</string>
    <string name="register_cashier_info_label_name">Name</string>
    <string name="register_cashier_info_label_branch">Branch</string>
    <string name="register_cashier_info_title">You Are Invited!</string>
    <string name="register_create_account_caption_subtitle">Username and password to sign in.</string>
    <string name="register_create_account_caption_title">Create your Account</string>
    <string name="register_create_account_cta_create_account">Create Account</string>
    <string name="register_create_account_error_msg_password_not_same">The passwords do not match.</string>
    <string name="register_create_account_label_re_enter_password">Re-enter Password</string>
    <string name="register_create_account_rule_6_to_10_characters">6 to 10 characters</string>
    <string name="register_create_account_rule_at_least_1_digit_1_special_character_except"><![CDATA[At least 1 digit & 1 special character, except %]]></string>
    <string name="register_create_account_rule_at_least_1_letter_1_numeral">At least 1 letter, 1 numeral</string>
    <string name="register_create_account_rule_at_least_1_uppercase_1_lowercase"><![CDATA["At least 1 uppercase & 1 lowercase "]]></string>
    <string name="register_create_account_rule_different_from_username">Different from username</string>
    <string name="register_create_account_rule_more_than_10_characters">More than 10 characters</string>
    <string name="register_create_account_rule_no_symbol">No % symbol</string>
    <string name="register_create_account_update_password_warning">Please update password every 90 days for security.</string>
    <string name="register_owner_info_caption_subtitle">Enter your info to activate account.</string>
    <string name="register_owner_info_cta_join_now">Join Now</string>
    <string name="register_owner_info_error_msg_phone_empty">Phone Number cannot be empty.</string>
    <string name="register_owner_info_label_nid">NID</string>
    <string name="register_owner_info_label_passport_no">Passport Number</string>
    <string name="register_owner_info_label_phone_number">Phone Number</string>
    <string name="register_owner_info_page_title">CUBC mBanking Info</string>
    <string name="register_owner_info_segment_cambodian">Cambodian</string>
    <string name="register_owner_info_segment_foreigner">Foreigner</string>
    <string name="register_re_enter_error_msg_pin_not_same">Please enter the same PIN.</string>
    <string name="register_re_enter_pin_subtitle">4-digit you just set.</string>
    <string name="register_re_enter_pin_title">Re-enter PIN</string>
    <string name="register_result_biometric_content">Use biometrics for a faster, secure experience.</string>
    <string name="register_result_biometric_title">Enable Biometric</string>
    <string name="register_set_pin_subtitle">4-digit for transactions.</string>
    <string name="register_set_pin_title">Create PIN</string>
    <string name="register_success_content_your_account_is_ready">Your account is ready.</string>
    <string name="register_success_cta_get_started">Get Started</string>
    <string name="register_success_title_all_set">All Set!</string>


    <string name="temp_add_cashier">Add Cashier</string>
    <string name="temp_add_new">Add New</string>
    <string name="temp_all_button_reset">Reset</string>
    <string name="temp_bind_limit_reach_content">The device has reached the binding limit. Please use another device to log in.</string>
    <string name="temp_binding_limit_reached">Binding Limit Reached</string>
    <string name="temp_cashier_deactivated_error">Cashier deactivate error,please retry</string>
    <string name="temp_click_try_again_to_refresh_error_code">Click try again to refresh.(%s)</string>
    <string name="temp_grow_your_business">Grow Your Business!</string>
    <string name="temp_hotline">Bank Hotline : %s</string>
    <string name="temp_incorrect_account_input">Incorrect username or password. Please check your details and try again.</string>
    <string name="temp_login_failed">Login Failed</string>
    <string name="temp_menu_add">Add</string>
    <string name="temp_nickname_can_t_be_empty">Nickname cannot be empty.</string>
    <string name="temp_no_branch_found_content">Please contact us to create one.</string>
    <string name="temp_no_branch_found_title">No Branch Found</string>
    <string name="temp_owner_manage_btn_cashiers">Cashiers</string>
    <string name="temp_owner_manage_btn_notifications">Notifications</string>
    <string name="temp_owner_manage_business_cta_cashiers">Cashiers</string>
    <string name="temp_owner_manage_business_disables">This business is disables.</string>
    <string name="temp_please_select_a_branch">Please Select A Branch</string>
    <string name="temp_register_owner_info_error_msg_phone_same_with_backend">Incorrect phone number. Please check and try again.</string>
    <string name="temp_select_branch">Select Branch</string>
    <string name="temp_title_to">To:</string>
    <string name="temp_todo_age_is_not_valid">Please enter a valid date of birth.</string>
    <string name="temp_dob_cannot_be_empty">Date of Birth cannot be empty.</string>
    <string name="temp_view_details">View details</string>
    <string name="temp_your_id_number_is_invalid">Your NID Number is invalid.</string>
    <string name="temp_activation_failed">Activation Failed</string>
    <string name="temp_todo_dob_cannot_be_empty">todo Dob cannot be empty</string>
    <string name="temp_security_settings">Security Settings</string>
    <string name="temp_settings">Settings</string>
    <string name="temp_merchant_id">Merchant ID:</string>
    <string name="temp_delete_my_account">Delete my Account</string>
    <string name="temp_logout">Logout</string>
    <string name="temp_privacy_policy">Privacy Policy</string>
    <string name="temp_version">Version</string>
    <string name="temp_manage_biometric">Manage Biometric</string>
    <string name="temp_forgot_pin">Forgot PIN</string>
    <string name="temp_change_pin">Change PIN</string>
    <string name="temp_manage_cashiers">Manage Cashiers</string>
    <string name="temp_unavailable_for_devices_linked_to_multiple_users">Unavailable for devices linked to multiple users.</string>
    <string name="temp_language_settings">Select Language</string>
    <string name="temp_are_you_sure_to_log_out_title">Confirm Log Out</string>
    <string name="temp_are_you_sure_to_log_out_content">Are you sure you want to log out?</string>
    <string name="temp_delete_my_account_title">Delete Account</string>
    <string name="temp_delete_my_account_content">To delete your account, please contact us for assistance.</string>
    <string name="temp_login_again_title">Log In Again</string>
    <string name="temp_login_again_content">Your settings have been updated. Please log in again to apply the changes.</string>
    <string name="temp_enable_screenshot_functionality">Enable Screenshot</string>
    <string name="temp_enable_screen_overlay_detection">Enable Screen Overlay</string>
    <string name="temp_biometric_settings">Manage Biometrics</string>
    <string name="temp_enable_fingerprint">Enable Fingerprint</string>
    <string name="temp_register_again">Register again</string>
    <string name="temp_overlay_screen_detected_content">A screen overlay has been detected. Please ensure your phone\'s security.</string>

    <string name="temp_enter_login_info">Enter Login Info</string>
    <string name="temp_please_enter_your_credentials_to_proceed">Please enter your credentials to proceed.</string>
    <string name="temp_enter_pin">Enter PIN</string>
    <string name="temp_enter_current_pin_to_reset">Enter current PIN to reset.</string>
    <string name="temp_pin_code_reset_successfully_please_use_the_new_pin_for_verification">PIN code reset successfully! Please use the new PIN for verification.</string>
    <string name="temp_disable_biometric_login_title">Disable Biometric Login?</string>
    <string name="temp_disable_biometric_login_content">You can re-enable biometrics anytime in settings.</string>
    <string name="temp_final_attempt">Final Attempt</string>
    <string name="temp_you_have_once_chance_left">After 1 more incorrect attempts, PIN will be Locked.</string>
    <string name="temp_unlock_pin_please_follow_the_steps_in_forgot_pin">To unlock PIN, please follow the steps in \"Forgot PIN\".</string>
    <string name="temp_pin_locked">PIN Locked</string>
    <string name="temp_username_cannot_be_empty">Username cannot be empty.</string>
    <string name="temp_password_cannot_be_empty">Password cannot be empty.</string>
    <string name="temp_account_locked">Account Locked</string>
    <string name="temp_too_many_failed_attempts_please_go_help_for_assistance">Too many failed attempts. Please go “Help” for assistance.</string>
    <string name="temp_verification_failed">Verification Failed</string>
    <string name="temp_incorrect_username_or_password_entered_please_check_your_details_and_try_again">Incorrect username or password entered. Please check your details and try again.</string>
    <string name="temp_your_new_password_is_ready">Your new password is ready.</string>
    <string name="temp_set_new_password">Set New Password</string>
    <string name="temp_enter_a_new_password_for_your_account">Enter a new password for your account.</string>
    <string name="temp_confirm_password">Confirm Password</string>
    <string name="temp_new_password">New Password</string>
    <string name="temp_change_password">Change Password</string>
    <string name="temp_please_update_your_password_every_90_days_for_security_purpose">Please update your password every 90 days for security purpose.</string>
    <string name="temp_to_keep_your_account_secure_please_change_your_password">To keep your account secure, please change your password.</string>
    <string name="temp_update_your_password">Update Your Password</string>
    <string name="temp_forget_password_title">Forget Password?</string>
    <string name="temp_please_reach_out_to_the_appropriate_representative_for_a_one_time_password">Please reach out to the appropriate representative for a one-time password.</string>
    <string name="temp_cashiers_your_supervisor">Cashiers: Your supervisor.</string>
    <string name="temp_owners_contact_us_directly">Owners: Contact us directly.</string>
    <string name="temp_if_multiple_users_are_registered_on_this_device_finger_will_be_unavailable">If multiple users are registered on this device, fingerprint authentication will be unavailable.</string>
    <string name="temp_fingerprint_register_again">If your fingerprint doesn’t work, please <![CDATA[<font color=#00994E>register it again</font>]]>.</string>
    <string name="temp_please_use_username_and_password_to_log_in_and_go_forgot_pin">Please log in first, then go “Forgot PIN” to unlock.</string>
    <string name="temp_please_contact_your_supervisor_for_details">Please contact your supervisor for details.</string>
    <string name="temp_account_deactivated">Account Deactivated</string>
    <string name="temp_please_contact_us_for_details">Please contact us for details.</string>
    <string name="temp_close_app_dialog_title">Leave CUBC Merchant?</string>
    <string name="temp_close_app_dialog_msg">Leaving CUBC Merchant will stop all ongoing processes.</string>
    <string name="temp_fido_biometric_not_supported_title">Biometric Not Supported</string>
    <string name="temp_fido_biometric_not_supported_content">Your device does not support biometric authentication.</string>
    <string name="temp_fido_your_fingerprint_is_ready">Your Fingerprint is ready.</string>
    <string name="temp_base_error_content">Something Went Wrong. Please try again or contact us! (%s)</string>
    <string name="temp_base_error_content_for_cashier">Something Went Wrong. Please try again or contact your supervisor! (%s)</string>
    <string name="temp_terms_and_privacy_policy_title">Terms &amp; Privacy Policy.</string>
    <string name="temp_register_set_pin_fail">Your account is ready! Set up your PIN via \"Forgot PIN\" for a seamless login next time.</string>
    <string name="temp_register_success_go_set_fido">Your account is ready! Set up your Fingerprint via \"Settings\" for a seamless login next time.</string>
    <string name="temp_biometrics_expired_title">Biometrics Expired</string>
    <string name="temp_biometrics_expired_content">Please use PIN to log in and register biometrics.</string>
    <string name="temp_unlock_screen">Please unlock your screen and retry biometrics, or log in with your PIN.</string>
    <string name="temp_verify_biometrics_title">Verify Biometrics</string>
    <string name="temp_verify_biometrics_content">Please try using your Fingerprint again.</string>
    <string name="temp_login_account_locked_title">Account Locked</string>
    <string name="temp_login_account_locked_content">Too many failed login attempts.\nPlease go \"Help\" for assistance.</string>
    <string name="temp_link_invalid_title">Link Invalid</string>
    <string name="temp_link_invalid_content">Please try another one or contact your supervisor</string>
    <string name="temp_register_no_branch_found_title">No Branch Found</string>
    <string name="temp_register_no_branch_found_content">You haven\'t been assigned to a branch yet.</string>
    <string name="temp_transaction_history">Transaction History</string>
    <string name="temp_start_tracking_business">Start Tracking Business</string>
    <string name="temp_select">Select</string>
    <string name="temp_filter">Filter</string>
    <string name="temp_select_date">Select Date</string>
    <string name="temp_all_sales">All Sales</string>
    <string name="temp_total_sales">Total Sales</string>
    <string name="temp_sales_in_khr">Sales in KHR</string>
    <string name="temp_sales_in_usd">Sales in USD</string>
    <string name="temp_no_more_items">You’re all caught up.</string>
    <string name="temp_search">Search</string>
    <string name="temp_payer_name">Payer Name</string>
    <string name="temp_start_your_search">Start Your Search</string>
    <string name="temp_received">Received</string>
    <string name="temp_from">From</string>
    <string name="temp_transaction_detail">Transaction Detail</string>
    <string name="temp_transaction_details">Transaction Details</string>
    <string name="temp_transaction_type">Transaction Type</string>
    <string name="temp_account_number">Account Number</string>
    <string name="temp_reference_number">Reference Number</string>
    <string name="temp_external_txn_ref">External Txn Ref</string>
    <string name="temp_please_select_at_least_a_branch">Please select at least a branch.</string>
    <string name="temp_today">Today</string>
    <string name="temp_please_select_a_range_within_31_days">Please select a range within 31 days.</string>
    <string name="temp_manage_view_and_search_cashier_details_here">Manage, view, and search Cashier details here.</string>
    <string name="temp_start_adding_cashier">Start Adding Cashier</string>
    <string name="temp_cashier_name">Cashier Name</string>
    <string name="temp_notification">Notification</string>
    <string name="temp_last_seven_days">Last 7 Days</string>
    <string name="temp_ealier">Ealier</string>
    <string name="temp_deeplink_logout_title">Log Out. Required</string>
    <string name="temp_deeplink_logout_content">Another user is currently logged in on this device. To proceed, please log them out.</string>
    <string name="temp_all_button_setting">Setting</string>
    <string name="temp_all_button_sure">Sure</string>
    <string name="temp_all_button_log_out">Log Out</string>
    <string name="temp_all_button_disable">Disable</string>
    <string name="temp_all_i_agree">I Agree</string>
    """

val lokalise=
    """
   <string name="B">Another user is currently logged in on this device. To proceed, please log them out.</string>
  <string name="B.10.47">CUBC mBanking Info.</string>
  <string name="B.12">You\'ve Registered!</string>
  <string name="B.13.50">Something Went Wrong</string>
  <string name="B.16.34">Username Taken</string>
  <string name="B.26">Please use username and password to login.</string>
  <string name="B.29.30">NID / Passport No.</string>
  <string name="B.3">Log Out Required</string>
  <string name="B.3.23">Activate Failed</string>
  <string name="B.37">Branch</string>
  <string name="B.39.20">Something Went Wrong. Please try again or contact us! (Error Code)</string>
  <string name="B.39.27">Service</string>
  <string name="B.39.51">Incorrect personal info. Please check and try again.</string>
  <string name="B.40">Join as a cashier via your phone within 72 hours.</string>
  <string name="B.44.37">The process will be terminated. Please contact us.</string>
  <string name="B.44.92">Call</string>
  <string name="B.472">Enter a new password for your account.</string>
  <string name="B.49">Your account is ready! Set up your Face ID via \"Settings\" for a seamless login next time.</string>
  <string name="B.62">Term &amp; Privacy Policy.</string>
  <string name="B.7.8">I agree to</string>
  <string name="B.74.77">Please choose a new username.</string>
  <string name="B.81.84">At least 1 letter &amp; 1 numeral</string>
  <string name="B.82">You’ve Registered!</string>
  <string name="B.83">Data Unsaved</string>
  <string name="B.83.35">Please try another one or contact your supervisor.</string>
  <string name="B.84.78">Passport No.</string>
  <string name="B.86.76">4-digit you just set.</string>
  <string name="B.87">Terms &amp; Policy.</string>
  <string name="B.87.71">Cambodian</string>
  <string name="B.88">The process will be terminated. Please contact us</string>
  <string name="B.90.9">Information won\'t be kept if you return to the last step.</string>
  <string name="B.93.68">Incorrect personal info. Please check your details and try again.</string>
  <string name="B.96">Link Invalid</string>
  <string name="B.98">Your account is ready! Set up your PIN via \"Forgot PIN\" for a seamless login next time.</string>
  <string name="B.99.3">Go</string>
  <string name="E">Manage Biometrics</string>
  <string name="E.10.23">Setting</string>
  <string name="E.11">Please try using your Face ID again.</string>
  <string name="E.13">If Face ID doesn’t work, register it again.</string>
  <string name="E.15">Don’w Allow</string>
  <string name="E.17.28">If your fingerprint doesn’t work, please register it again.</string>
  <string name="E.18">I Agree</string>
  <string name="E.19">We need permission to access your FaceID for better experience for login.</string>
  <string name="E.20">Terms &amp; Privacy Policy.</string>
  <string name="E.22">Biometric Not Supported</string>
  <string name="E.22.45">Please unlock your screen and try again.</string>
  <string name="E.24">New OTP sent</string>
  <string name="E.24.49">  Enable Biometrics Failed</string>
  <string name="E.29">I Agree</string>
  <string name="E.3">Your Biometrics is ready.</string>
  <string name="E.30">Biometrics disabled due to multiple merchant IDs.</string>
  <string name="E.34">Failed to enable Face ID. Please unlock the screen and try again.</string>
  <string name="E.34.93">Please allow CUBC Merchant accessing your Face ID.</string>
  <string name="E.36">Verify Biometrics</string>
  <string name="E.39.22">Enabled Face ID</string>
  <string name="E.41">Manage Biometric </string>
  <string name="E.49">Biometric Access Required</string>
  <string name="E.53">Settings  Security Settings</string>
  <string name="E.55">Your device does not support biometric authentication.</string>
  <string name="E.60">Log out</string>
  <string name="E.62">Manage Biometric </string>
  <string name="E.69.47">Register Face ID again</string>
  <string name="E.70">Face ID disabled due to multiple linked merchant IDs.</string>
  <string name="E.73">Fail Limits Reached</string>
  <string name="E.74">Your Fingerprint is ready.</string>
  <string name="E.76">Done</string>
  <string name="E.8">If multiple users are registered on this device, Face ID will be unavailable.</string>
  <string name="E.8.91">Please allow CUBC Merchant accessing your FIngerprint.</string>
  <string name="E.80">Please try using your Fingerprint again.</string>
  <string name="E.81">Delete my Account</string>
  <string name="E.83">Allow</string>
  <string name="E.83.62">Disagree</string>
  <string name="E.9">Allow “CUBC Merchant” to use FaceID?</string>
  <string name="E.9.95">If your Face ID doesn’t work, please register it again. </string>
  <string name="E.91">Replace or paste your app screenshot here</string>
  <string name="E.93.79">If multiple users are registered on this device, Finger cannot be used</string>
  <string name="E.94.100">Failed to enable FaceID. Please unlock the screen and try again.</string>
  <string name="E.95">Permission Request</string>
  <string name="E.98.48">Your Face ID is ready.</string>
  <string name="G">Account Transaction</string>
  <string name="G.45">2.00 USD is paid by KHQR KEO Nika on 08/05/2024. \nContent from SEAlink</string>
  <string name="G.51">Ealier</string>
  <string name="G.57">Received from Sealink</string>
  <string name="G.59">Payment Received!</string>
  <string name="G.66">Last 7 Days</string>
  <string name="NS_User_Notifications_Usage_Description_">To get timely info and updates from \"CUBC Merchant\".</string>
  <string name="a">Resend 01:59</string>
  <string name="a.1">You\'re about to be logged out. Tap “Stay” to stay signed in.</string>
  <string name="a.10">Too many failed login attempts. Please go \"Help\" for assistance.</string>
  <string name="a.100">Call +855 127 172 18</string>
  <string name="a.11">Session Timeout</string>
  <string name="a.2">Please enter username and password to proceed.</string>
  <string name="a.29">CUBC</string>
  <string name="a.45.91">Too many failed login attempts. Please use your PIN to login.</string>
  <string name="a.47">Binding Limit Reached</string>
  <string name="a.60">Too many failed attempts. Please try again tomorrow.</string>
  <string name="a.60.15">Merchant </string>
  <string name="a.64">ErrorMsg</string>
  <string name="a.64_copy">Please enter correct OTP.</string>
  <string name="a.84.68">Account Locked</string>
  <string name="a.90">Too many failed login attempts. Please use your username and password to login.</string>
  <string name="a.97">Biometric Locked</string>
  <string name="a.97.22">The device has reached the binding limit. Please use another device to log in.</string>
  <string name="all_alert_content_back">Information won’t be kept if you return to the last step.</string>
  <string name="all_alert_content_disconnection">Check your Internet connection and reload the page again.</string>
  <string name="all_alert_content_not_get_code">If you\'re having trouble receiving the code. Please try again later or contact us.</string>
  <string name="all_alert_title_not_get_code">Didn\'t Get OTP Code?</string>
  <string name="all_alert_title_oops">Oops!</string>
  <string name="all_alert_title_went_wrong">Something Went Wrong</string>
  <string name="all_base_contact_us">Contact Us</string>
  <string name="all_base_select">Select</string>
  <string name="all_button_apply">Apply</string>
  <string name="all_button_call">Call</string>
  <string name="all_button_cancel">Cancel</string>
  <string name="all_button_close">Close</string>
  <string name="all_button_confirm">Confirm</string>
  <string name="all_button_create">Create</string>
  <string name="all_button_done">Got It</string>
  <string name="all_button_got_it">Got It</string>
  <string name="all_button_help">Help</string>
  <string name="all_button_later">Later</string>
  <string name="all_button_leave">Leave</string>
  <string name="all_button_login">Log In</string>
  <string name="all_button_next">Next</string>
  <string name="all_button_ok">OK</string>
  <string name="all_button_please_retry">Please Retry</string>
  <string name="all_button_remove">Remove</string>
  <string name="all_button_reset">Reset</string>
  <string name="all_button_reset_password">Change Password</string>
  <string name="all_button_save">Save</string>
  <string name="all_button_send_invitation">Send Invitation</string>
  <string name="all_button_share">Share</string>
  <string name="all_button_stay">Stay</string>
  <string name="all_button_sure">Sure</string>
  <string name="all_button_try_again">Try Again</string>
  <string name="all_button_update">Update</string>
  <string name="all_cashier">Cashier</string>
  <string name="all_label_Invite">Invite</string>
  <string name="all_label_all">All</string>
  <string name="all_label_deactivate">Deactivate</string>
  <string name="all_label_dob">Date of Birth (DD-MM-YYYY)</string>
  <string name="all_label_no_data_found_">No Data Found</string>
  <string name="all_label_to">To</string>
  <string name="b">Cancel</string>
  <string name="b.31">You haven\'t been assigned to a branch yet.</string>
  <string name="b.37">Call</string>
  <string name="b.39">Apply</string>
  <string name="b.6">Got It</string>
  <string name="base_alert_notification_title">Notification Access Required</string>
  <string name="base_alert_notifications_content">Please go to \"Device Settings\" to enable notifications.</string>
  <string name="base_alert_unlink_content">Unlink “這邊請帶入 CashierName” from this branch. You can re-link anytime.</string>
  <string name="base_alert_unlink_title">Confirm to Unlink?</string>
  <string name="base_back_page_alert_content">Information won\'t be kept if you return to the last step.</string>
  <string name="base_back_page_alert_title">Data Unsaved</string>
  <string name="base_birth_hint">Date of Birth</string>
  <string name="base_contact_bottom_sheet_content">For applying a CUBC merchant account or recover username, please contact us. We are pleased to assist you 24/7.</string>
  <string name="base_contact_bottom_sheet_device_binding_content">For your security, complete device binding to continue using CUBC Merchant.</string>
  <string name="base_contact_bottom_sheet_title">Need Help?</string>
  <string name="base_fido_fail_limit_terminated_message">The process will be terminated. Please try again later. (Error Code)</string>
  <string name="base_hint_passport">Passport</string>
  <string name="base_input_error_dob_empty">Date of Birth cannot be empty.</string>
  <string name="base_input_error_follow_rule">Please follow the rule.</string>
  <string name="base_input_error_id_number_empty">NID Number cannot be empty.</string>
  <string name="base_input_error_id_number_invalid">ID Number cannot be empty.</string>
  <string name="base_input_error_nickname_empty">Nickname cannot be empty</string>
  <string name="base_input_error_passport_number_empty">Passport Number cannot be empty.</string>
  <string name="base_input_error_phone_number_empty">Phone Number cannot be empty.</string>
  <string name="base_input_error_phone_number_invalid">Phone Number is invalid.</string>
  <string name="base_label_nickname">Nickname</string>
  <string name="base_login_alert_incorrect_input_msg">Incorrect username or password. Please check your details and try again.</string>
  <string name="base_login_alert_login_failed_title">Login Failed</string>
  <string name="base_login_button_forgot">Forgot?</string>
  <string name="base_login_label_password">Password</string>
  <string name="base_login_label_user_name">Username</string>
  <string name="base_offline_dialog_content">Please check your connection and reload.</string>
  <string name="base_offline_dialog_title">You\'re Offline</string>
  <string name="base_otp_resend">Resend</string>
  <string name="base_otp_resend_limit_reached">Resend Limit Reached</string>
  <string name="base_otp_send_api_daily_left_count_equal_zero_title">Error Limit Reached</string>
  <string name="base_otp_send_otp">Send OTP</string>
  <string name="base_otp_title">Enter OTP on</string>
  <string name="base_permission_button_not_allow">Don’t Allow</string>
  <string name="base_permission_gallery_alert_content">Please go to \"Device Settings\" to enable access.</string>
  <string name="base_register_error_msg_invalid_dob">Please enter a valid date of birth.</string>
  <string name="base_register_error_msg_invalid_nid">Your NID Number is invalid.</string>
  <string name="base_rules_input_t24">Only accept these special characters - . ( ) ,</string>
  <string name="base_terms_checkbox_foreword_title">I agree</string>
  <string name="base_terms_checkbox_title">Terms &amp; Privacy Policy</string>
  <string name="base_terms_uncheck_alert_content">Please agree to CUBC T&amp;C Policy to continue.</string>
  <string name="base_terms_uncheck_alert_title">Terms Agreed</string>
  <string name="base_upgrade_version_dialog_content">A new app version is ready. Please update to continue. This will only take a few minutes.</string>
  <string name="base_upgrade_version_dialog_title">Time to Update</string>
  <string name="business_management_add_new_cashiers">New Cashier</string>
  <string name="business_management_alert_deactivate_msg">All info related to \"Cashier Name\" will be permanently deleted and cannot be undone.</string>
  <string name="business_management_alert_deactivate_title">Confirm to Deactivate</string>
  <string name="business_management_alert_name_taken_msg_">Please use a new name.</string>
  <string name="business_management_alert_name_taken_title">Name Taken</string>
  <string name="business_management_alert_phone_taken_msg">Please use a new phone number.</string>
  <string name="business_management_alert_phone_taken_title">Phone Number Taken</string>
  <string name="business_management_alert_reset_limit_msg">Too many password reset attempts. Please try again tomorrow.</string>
  <string name="business_management_alert_reset_limit_title_">Reset Limit Reached</string>
  <string name="business_management_alert_reset_password_msg">A temporary password will be sent to \"Cashier Name\" to reset password.</string>
  <string name="business_management_alert_reset_password_title">Reset Password Request</string>
  <string name="business_management_bottom_sheet_branch_info">Branch Info</string>
  <string name="business_management_bottom_sheet_notify_content">Manage notifications for each branch individually.</string>
  <string name="business_management_bottom_sheet_notify_title">Stay Updated!</string>
  <string name="business_management_bottom_sheet_title">Link Branch</string>
  <string name="business_management_branch_info">Info</string>
  <string name="business_management_business_deactivated_description">\"Business NameBusiness Name\" is deactivated.</string>
  <string name="business_management_caption_title_confirmation">Confirmation</string>
  <string name="business_management_caption_title_detail">Cashier Management</string>
  <string name="business_management_caption_title_enter_cashier_">Enter Cashier Info</string>
  <string name="business_management_caption_title_pin">Enter PIN</string>
  <string name="business_management_cashier_Unlinked_toast_content">Cashier Unlinked</string>
  <string name="business_management_cashier_archive_date_notice">All data will be archived on 7 Jun 2024.</string>
  <string name="business_management_cashier_data_archive_note">Cashier data will be archived on June 7.</string>
  <string name="business_management_cashier_last_invitation_date_notice_">Last invitation link was sent on 7 Jun 2024.</string>
  <string name="business_management_cashier_state_active">Active</string>
  <string name="business_management_cashier_state_deactivated">Deactivated</string>
  <string name="business_management_cashier_state_locked">Locked</string>
  <string name="business_management_cashier_state_pending">Pending</string>
  <string name="business_management_cashier_state_resetting">Resetting</string>
  <string name="business_management_cashier_state_restricted">Restricted</string>
  <string name="business_management_cashiers_layer_header">Linked Cashiers</string>
  <string name="business_management_deactivated_branch_layer_content">Branch is deactivated. Contact us for more info.</string>
  <string name="business_management_deactivated_branch_message">Branch is deactivated./n Contact us to bring it back!</string>
  <string name="business_management_deactivated_branch_notice">All branches deactivated. Contact us for details.</string>
  <string name="business_management_deactivated_branches_notice_">All branches deactivated. Contact us for details.</string>
  <string name="business_management_empty_branch_notice_layer_content">Set up branches to unlock smarter business management!</string>
  <string name="business_management_empty_branch_notice_layer_cta">No Branch Yet</string>
  <string name="business_management_former_cashiers_layer_content">Former Cashiers</string>
  <string name="business_management_label_to">To:</string>
  <string name="business_management_last_invitation_link_sent_notice">Last invitation link was sent on 7th Jun.</string>
  <string name="business_management_link_cashier_cta">Link</string>
  <string name="business_management_link_existing_title">Link Existing Cashiers</string>
  <string name="business_management_no_linked_cashiers_layer_content">No Linked Cashier</string>
  <string name="business_management_notification">Notification</string>
  <string name="business_management_notification_branch_content">Ｍanage notifications for each branch individually. </string>
  <string name="business_management_result_label_view_details">View details</string>
  <string name="business_management_result_link_cashiers_hint">Click to see more details</string>
  <string name="business_management_result_link_cashiers_message_">Link 6 Cashiers</string>
  <string name="business_management_result_link_single_cashiers_message">Link 1 Cashier</string>
  <string name="business_management_result_link_success_message">All Cashiers are successfully linked.</string>
  <string name="business_management_result_share_link_message">Share link to invite the new cashier.</string>
  <string name="business_management_result_single_link_success_message">Cashier is successfully linked.</string>
  <string name="business_management_title_device_information">Device Information</string>
  <string name="business_management_toast_cashier_deactivate_error">Cashier deactivate error, please retry</string>
  <string name="business_management_toast_cashier_deactivated_">Cashier deactivated</string>
  <string name="business_management_toast_cashier_unlink_error_">Cashier unlinked error, please retry</string>
  <string name="business_management_toast_cashier_unlinked">Cashier unlinked</string>
  <string name="business_management_toast_reset_link_error_">Reset link error, please retry</string>
  <string name="business_management_toast_reset_link_sent">Reset link sent</string>
  <string name="business_management_transaction_layer_content">No Transaction History</string>
  <string name="c.47">Manage, view, and search Cashier details here.</string>
  <string name="c.49">Add</string>
  <string name="c.83">Cashier Name</string>
  <string name="c.9">Start Adding Cashier</string>
  <string name="d">Reset Password</string>
  <string name="d.32">“Business NameBusiness Name” is deactivated.</string>
  <string name="d.34">To</string>
  <string name="d.56">Resetting</string>
  <string name="e">Enable Fingerprint</string>
  <string name="e.1">Manage Cashiers</string>
  <string name="e.1.89">20 Jun 2025 → 26 Jun 2025</string>
  <string name="e.1.94">May</string>
  <string name="e.10">To keep your account secure, please change your password.</string>
  <string name="e.11">July</string>
  <string name="e.15">Unavailable for devices linked to multiple users.</string>
  <string name="e.15.16">Please enter your credentials to proceed.</string>
  <string name="e.15.98">PIN Locked</string>
  <string name="e.18">PIN code reset successfully! Please use the new PIN for verification.</string>
  <string name="e.19">Too many failed login attempts. Please go “Help” for assistance.</string>
  <string name="e.2">Please contact your supervisor for details.</string>
  <string name="e.2.9">Incorrect PIN entered.</string>
  <string name="e.20">Enable Face ID</string>
  <string name="e.20.19">If you’re having trouble receiving the code. Please try again later or contact us.</string>
  <string name="e.21">Forgot PIN</string>
  <string name="e.21.83">Please unlock your screen and retry biometrics, or log in with your PIN.</string>
  <string name="e.23">Final Attempt</string>
  <string name="e.24">Are you sure you want to log out?</string>
  <string name="e.27">Select Language</string>
  <string name="e.27.71">Aug</string>
  <string name="e.29">ErrorMSG</string>
  <string name="e.3">Delete Account</string>
  <string name="e.30">Friendly Remind</string>
  <string name="e.34">Version</string>
  <string name="e.34.34">Manage Biometric</string>
  <string name="e.35">Didn’t Get OTP Code?</string>
  <string name="e.38">PIN</string>
  <string name="e.41">Account Deactivated</string>
  <string name="e.46">Change PIN</string>
  <string name="e.46.64">Any unsaved progress will be lost. Do you want to continue?</string>
  <string name="e.48">Change Password</string>
  <string name="e.49">Manage Biometrics</string>
  <string name="e.49.98">Confirm Password</string>
  <string name="e.5">Delete Account</string>
  <string name="e.53">You have once chance left.</string>
  <string name="e.54">You’ve reached the SMS resend limit. Please try again later.</string>
  <string name="e.54.87">Jun</string>
  <string name="e.56">Please enter your credentials to proceed.</string>
  <string name="e.58">Your settings have been updated. Please log in again to apply the changes.</string>
  <string name="e.6">Log Out</string>
  <string name="e.6.57">New Password</string>
  <string name="e.60">After 1 more incorrect attempts, PIN will be Locked.</string>
  <string name="e.61">Current Username</string>
  <string name="e.61.64">12 Mar 2025</string>
  <string name="e.63">Incorrect username or password entered. Please check your details and try again.</string>
  <string name="e.63.51">Wrong PIN entered.</string>
  <string name="e.64">Current Password</string>
  <string name="e.64.99">Input your current username and password.</string>
  <string name="e.65">Disable Biometric Login?</string>
  <string name="e.65.28">02 Jan 2025</string>
  <string name="e.66">To delete your account, please contact us for assistance.</string>
  <string name="e.66.98">Please update your password every 90 days for security purpose.</string>
  <string name="e.68">Jun 2025</string>
  <string name="e.69">Forget Password?</string>
  <string name="e.7">Please contact your supervisor to unlock.</string>
  <string name="e.73">Contact your supervisor for a one-time password.</string>
  <string name="e.73.82">Your new password is ready.</string>
  <string name="e.74.92">Apr</string>
  <string name="e.75">Please use PIN to log in and register biometrics.</string>
  <string name="e.76">Update Your Password</string>
  <string name="e.77">You can re-enable biometrics anytime in settings.</string>
  <string name="e.78">A screen overlay has been detected. Please ensure your phone\'s security.</string>
  <string name="e.78.64">12 transactions</string>
  <string name="e.79">Enter current PIN to reset.</string>
  <string name="e.8">Settings</string>
  <string name="e.82">Please contact us for details.</string>
  <string name="e.82.74">To unlock PIN, please follow the steps in \"Forgot PIN\".</string>
  <string name="e.83">The process will be terminated. Please try again later.  (Error Code)</string>
  <string name="e.84">Verification Failed</string>
  <string name="e.84.30">Contact us for a one-time password.</string>
  <string name="e.84.37">Start Your Search</string>
  <string name="e.85">Confirm Log Out</string>
  <string name="e.86">Please log in first, then go “Forgot PIN” to unlock.</string>
  <string name="e.86.51">Start Tracking Business</string>
  <string name="e.87">Enter Login Info</string>
  <string name="e.9">Set New Password</string>
  <string name="e.91">Log Out</string>
  <string name="e.91.52">Privacy Policy</string>
  <string name="e.92">Enable Screen Overlay</string>
  <string name="e.93">Register again</string>
  <string name="e.93.94">Biometrics Expired</string>
  <string name="e.97">Enable Screenshot</string>
  <string name="e.97.47">Security Settings</string>
  <string name="e.98">Confirm to Log Out</string>
  <string name="e.99">Log In Again</string>
  <string name="home_alert_api_error_refresh_msg">Click try again to refresh.</string>
  <string name="home_alert_no_branch_msg">Please contact us to create one.</string>
  <string name="home_alert_no_branch_title">No Branch Found</string>
  <string name="home_alert_not_branch_msg">Please contact us to create one.</string>
  <string name="home_go_select_business_title">Grow Your Business!</string>
  <string name="home_khqr_button_title_show_qr">Show QR</string>
  <string name="home_membership_code">Membership Code</string>
  <string name="home_select_branch_title">Select Branch</string>
  <string name="home_toast_currency_changed">Currency Changed</string>
  <string name="home_toast_membership_code_applied">Membership Code Applied</string>
  <string name="home_toast_membership_code_removed">Membership Code Removed</string>
  <string name="home_toast_pleas_select_a_branch">Please Select A Branch</string>
  <string name="login_binding_bottom_sheet_btn_start">Start</string>
  <string name="login_binding_bottom_sheet_title">Get Ready!</string>
  <string name="login_home_already_applied_offline">Already Applied Offline?</string>
  <string name="login_home_btn_register">Register</string>
  <string name="login_not_me_bottom_sheet_new_user">New User</string>
  <string name="login_not_me_bottom_sheet_other_users">Other Users</string>
  <string name="login_pin_hi">Hi,</string>
  <string name="login_pin_not_you">Not You?</string>
  <string name="login_title_welcome_to">Welcome to</string>
  <string name="qrcode_alert_content_error_min_amount">The amount must be greater than 100 Cambodian riel to proceed.</string>
  <string name="qrcode_bank_hotline">Bank Hotline : %s</string>
  <string name="qrcode_error_msg_generate_failed">We couldn\'t generate the QR code at this time. Please try Again.</string>
  <string name="qrcode_error_msg_min_amount">Amount exceeds the 12-character limit. Please reduce to continue.</string>
  <string name="qrcode_error_title_exceed_amount">Amount Limit Exceeded</string>
  <string name="qrcode_error_title_generate_failed">Generate QR Code Failed</string>
  <string name="qrcode_error_title_min_amount">Minimum Amount Required</string>
  <string name="qrcode_expired_alert_msg">Please generate a new code to continue.</string>
  <string name="qrcode_expired_alert_title">QR Code Expired.</string>
  <string name="qrcode_toast_khqr_save_success">KHQR Saved</string>
  <string name="qrcode_toast_khqr_share_success">KHQR Shared</string>
  <string name="register_cashier_info_alert_activate_fail_title">Activation Failed</string>
  <string name="register_cashier_info_alert_incorrect_phone_msg">Incorrect phone number. Please check and try again.</string>
  <string name="register_cashier_info_label_by">by</string>
  <string name="register_cashier_info_label_name">Name</string>
  <string name="register_cashier_info_label_role">Role</string>
  <string name="register_cashier_info_title">You Are Invited!</string>
  <string name="register_create_account_caption_subtitle">Username and password to sign in.</string>
  <string name="register_create_account_caption_title">Create your Account</string>
  <string name="register_create_account_cta_create_account">Create Account</string>
  <string name="register_create_account_error_msg_password_not_same">The passwords do not match.</string>
  <string name="register_create_account_label_re_enter_password">Re-enter Password</string>
  <string name="register_create_account_rule_6_to_10_characters">6 to 10 characters</string>
  <string name="register_create_account_rule_at_least_1_digit_1_special_character_except">At least 1 digit &amp; 1 special character, except %</string>
  <string name="register_create_account_rule_at_least_1_letter_1_numeral">At least 1 letter, 1 numeral</string>
  <string name="register_create_account_rule_at_least_1_uppercase_1_lowercase">At least 1 uppercase &amp; 1 lowercase</string>
  <string name="register_create_account_rule_different_from_username">Different from username</string>
  <string name="register_create_account_rule_more_than_10_characters">More than 10 characters</string>
  <string name="register_create_account_rule_no_symbol">No % symbol</string>
  <string name="register_create_account_update_password_warning">Please update password every 90 days for security.</string>
  <string name="register_owner_info_caption_subtitle">Enter your info to activate account.</string>
  <string name="register_owner_info_cta_join_now">Join Now</string>
  <string name="register_owner_info_label_nid">NID</string>
  <string name="register_owner_info_label_passport_no">Passport Number</string>
  <string name="register_owner_info_label_phone_number">Phone Number</string>
  <string name="register_owner_info_page_title">CUBC mBanking Info</string>
  <string name="register_owner_info_segment_cambodian">Cambodian</string>
  <string name="register_owner_info_segment_foreigner">Foreigner</string>
  <string name="register_re_enter_error_msg_pin_not_same">Please enter the same PIN.</string>
  <string name="register_re_enter_pin_title">Re-enter PIN</string>
  <string name="register_result_biometric_content">Use biometrics for a faster, secure experience.</string>
  <string name="register_result_biometric_title">Enable Biometric</string>
  <string name="register_set_pin_subtitle">4-digit for transactions.</string>
  <string name="register_set_pin_title">Create PIN</string>
  <string name="register_success_content_your_account_is_ready">Your account is ready.</string>
  <string name="register_success_cta_get_started">Got It</string>
  <string name="register_success_title_all_set">All Set!</string>
  <string name="search_empty_state_message">Start Your Search</string>
  <string name="transaction_history_date_today_label">Today</string>
  <string name="transaction_history_details_cashier_title">Cashier</string>
  <string name="transaction_history_details_external_reference_title">External Txn Ref</string>
  <string name="transaction_history_details_reference_number_title">Reference Number</string>
  <string name="transaction_history_details_title">Transaction Details</string>
  <string name="transaction_history_details_type_title">Transaction Type</string>
  <string name="transaction_history_end_of_list_message">You’re all caught up.</string>
  <string name="transaction_history_filter_all_branches">All Branches</string>
  <string name="transaction_history_filter_title">Filter</string>
  <string name="transaction_history_label">Transaction History</string>
  <string name="transaction_history_sales_in_khr">Sales in KHR</string>
  <string name="transaction_history_sales_in_usd">Sales in USD</string>
  <string name="transaction_history_search_payer_name_hint">Payer Name</string>
  <string name="transaction_history_search_title">Search</string>
  <string name="transaction_history_select_business_title">Select Business</string>
  <string name="transaction_history_select_date_title">Select Date</string>
  <string name="transaction_history_toast_branch_required">Please select at least a branch.</string>
  <string name="transaction_history_toast_date_range_limit">Please select a range within 31 days.</string>
  <string name="transaction_history_total_sales_title">Total Sales</string>
  <string name="transaction_history_transfer_method_bakong">Bakong Transfer</string>
  <string name="transaction_history_transfer_method_bank">Bank Transfer</string>
  <string name="transaction_history_transfer_method_cubc">CUBC Transfer</string>
  <string name="棄用_home_select_branch_title">Other Branches</string>
  <string name="重複_a.19.66">Don’t Allow</string>
  <string name="重複_a.22">Membership Code</string>
  <string name="重複_a.25">Share</string>
  <string name="重複_a.28">Share</string>
  <string name="重複_a.3">Save</string>
  <string name="重複_a.33">Got It</string>
  <string name="重複_a.35.13">Apply</string>
  <string name="重複_a.46">OK</string>
  <string name="重複_a.56.60">Save</string>
  <string name="重複_a.66">Got It</string>       
    """